name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: praand/demo

jobs:

  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

  build_image:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag $IMAGE_NAME:test2
       docker save $IMAGE_NAME:test2 > /tmp/demo.tar
    - name: Upload image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: demo-image
        path: /tmp/demo.tar

  scan_image:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: demo-image
        path: /tmp
    - name: Load image
      run: |
          docker load --input /tmp/demo.tar
          docker image ls -a 
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'praand/demo:test2'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  push_image:
    needs: scan_image
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_TOKEN" | docker login -u praand --password-stdin
    - name: Tag and push the Docker images
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag $IMAGE_NAME:test2 $IMAGE_NAME:$GIT_SHA
        docker push $IMAGE_NAME:$GIT_SHA
        docker push  $IMAGE_NAME:test2

  sonarCloud:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
