name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag praand/demo:latest
    - name: Tag the Docker image
      run: .
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag $DOCKER_USERNAME/demo:latest $DOCKER_USERNAME/demo:$GIT_SHA
        
