name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_TOKEN" | docker login -u praand --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag praand/demo:latest
    - name: Tag the Docker image
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag praand/demo:latest praand/demo:$GIT_SHA
    - name: Push the Docker images
      run: |
        docker push praand/demo:$GIT_SHA
        docker push  praand/demo:latest
